[[pages]]
path="src/Home.py"
name="Home"
icon="ğŸ "

[[pages]]
path="src/app_pages/00_Prompt_Smith.py"
name="Prompt Smith"
icon="ğŸ§™ğŸ»â€â™€ï¸"

[[pages]]
path="src/app_pages/01_Segment_Architect.py"
name="Segment Architect"
icon=":bar_chart:"

[[pages]]
path="src/app_pages/02_Content_Personalizer.py"
name="Content Personalizer"
icon=":white_check_mark:"

[[pages]]
path="src/app_pages/03_Message_Dispatcher.py"
name="Message Dispatcher"
icon="ğŸª„"